### ISSUE TITLE
DAE test with CTSM is inordinately slow

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CMEPS#175]
The DAE test with CTSM is much slower than it should be...

DAE_N2_D_Lh12_Vnuopc.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.clm-DA_multidrv

The MCT version takes less than 20 minutes which is reasonable since this is only a 12 hour test at a course resolution. @billsacks found for the CMEPS test to run to completion it took 30X the time of the MCT version. That would mean giving it 10 hours wallclock time, which is quite unreasonable.

I'm not sure if this is a problem in CMEPS or in the CTSM NUOPC cap. But, this seems the right place to put it for visibility in the CMEPS project.

**Comment by jedwards4b** [comment]
@ekluzek _N2_ is not supported in cmeps the correct option is _C2_

**Comment by jedwards4b** [comment]
Running the test DAE_C2_D_Lh12_Vnuopc.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.clm-DA_multidrv
I see that the process of creating finidat_interp_dest files for the land model is happening completely serially.   What prevents these files being created concurrently?

**Comment by ekluzek** [comment]
@jedwards4b thanks for that correction. In the discussion @billsacks did try both C2 and N2 and both had the same behavior. But, it's good to know that we should change the test to _C2. We currently have the test as _N2, but will change it to _C2.

**Comment by ekluzek** [comment]
From looking at the code it's not explicitly serial. But, I think there's likely a lot of hidden synchronization points. It's only using MPI it doesn't have any OMP looping (this specific test is MPI only).

@billsacks can you comment on what @jedwards4b says about the finidat_interp_dest appearing to be written serially?

**Comment by jedwards4b** [comment]
My next question is about the DAE test itself.  It seems that the purpose of the test is to run twice, on the second run a da script is invoked and the two case results are compared.   It doesn't seem that there is a need for restart files here and continue_run should be false in both cases, so I tried setting REST_OPTION=none.   This causes case1 to run much faster but case2 fails because CONTINUE_RUN=True and there are no restarts.   I've looked through the dae.py and system_tests_compare_two.py and cannot figure out where or why this is happening.

**Comment by billsacks** [comment]
@jedwards4b - First off, thanks a lot for looking into this!

> I see that the process of creating finidat_interp_dest files for the land model is happening completely serially. What prevents these files being created concurrently?

Thanks for bringing this to our attention. Can you describe in more detail what you're seeing and how it differs from what you'd expect to see? I don't understand this well enough to be able to comment without having more information. I know that the *reading* of the *source* file needs to be done differently, since it's typically on a different grid from the model run, but I would have thought that the reading & writing of the destination file was done the same as normal for a restart file; if that's not the case, then I think something is being done differently from how it should be.

> N2 is not supported in cmeps the correct option is C2

Currently the DAE test explicitly sets MULTI_DRIVER in the testmod, so from my testing, it looked like setting _N2 with MULTI_DRIVER ends up accomplishing the same thing as _C2. I chose to leave it as is so that it stays the same as the existing MCT test, but I guess we could change both of them to use _C2 and then get rid of MULTI_DRIVER from the testmod.

> My next question is about the DAE test itself.

I don't know much about this test, but if this is supposed to mimic how DA is actually done, then I would expect it to do something with restarts...  I'm wondering if this is somehow tied in with the setting of DATA_ASSIMILATION_SCRIPT / DATA_ASSIMILATION_CYCLES? Is there an "owner" / responsible person for DA in CESM right now who could be called on to help with this?

**Comment by billsacks** [comment]
This may be fixed; @ekluzek let's look at how long this is taking in recent runs.

**Comment by ekluzek** [comment]
This is now reasonable in my latest testing. It's still a factor of 2-3 longer than MCT, but no longer an order of magnitude. The result give for RUN in TestStatus is 829 for NUOPC and 359 for MCT, but that's workable. So let's call this done.
