### ISSUE TITLE
Modify the default value of flux_convergence to be 0.01 rather than 0.0

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CMEPS#80]
Modify the default value of flux_convergence to be 0.0 rather than 0.01.

**Comment by billsacks** [comment]
Based on discussions with @mvertens and @jedwards4b and email communication with Gokhan, and especially the comment here:

https://github.com/ESCOMP/CESM_CPL7andDataComps/blob/6c75d64dcc9e1f85310add53518aa4ec4889fc55/driver/cime_config/namelist_definition_drv.xml#L744-L759

we think what is actually meant here is the opposite of what @mvertens first wrote: In fact, we should modify the default value to be 0.01 rather than 0.0.

I am editing the title accordingly.

**Comment by billsacks** [comment]
@mvertens @jedwards4b @briandobbins - if this is still an issue, it seems like it might be important to resolve soon-ish?

**Comment by billsacks** [comment]
Thanks @jedwards4b !
